CREATE OR REPLACE VIEW VIEW_AGREEMENT_FILE_INFO AS
SELECT ROWNUM as ID_DOCUMENT_FILES_KEY, v.* 
    FROM (
        SELECT C.IS_ACTIVE,
            F.ID_OBJECT_KEY AS ID_CONFIG_KEY,
            C.ID_USER_CREATE_KEY AS ID_CREATE_BY,
            C.CONFIG_GROUP , 
            C.CONFIG_SUB_GROUP, 
            C.VALUE4 AS TX_STATUS,
            C.DTT_CREATE AS DT_CREATE, 
            F.TX_FILE_NAME, 
            REGEXP_SUBSTR(F.TX_FILE_PATH, '[^\\]+$', 1, 1) AS TX_FILE_PATH,
            --F.TX_FILE_PATH, 
            F.TX_OBJECT_TYPE  
        FROM T_CONFIGURATION C
        RIGHT JOIN T_FILES F ON C.CONFIG_ID = F.ID_OBJECT_KEY 
        AND F.TX_OBJECT_TYPE = 'SConfiguration'
        WHERE C.IS_ACTIVE = 1
            AND C.IS_ACTIVE = F.IS_ACTIVE
            AND C.CONFIG_GROUP IS NOT NULL
            AND C.CONFIG_SUB_GROUP IS NOT NULL
        ORDER BY C.CONFIG_ID DESC
    ) v;