CREATE OR REPLACE VIEW VIEW_DOWNLOAD_SIGNATURE AS
SELECT ROWNUM AS ID_DOWNLOAD_SIGNATURE_KEY, V.* FROM 
    (
        SELECT 
            CASE
                WHEN L.TX_ACTIVITY_TYPE = 'DOWNLOAD_SIGANTURE' THEN 'PA'
                WHEN L.TX_ACTIVITY_TYPE = 'DOWNLOAD_FULL_SIGANTURE' THEN 'FULL BOOKLET'
                ELSE ''
            END AS TX_SEEKING_FOR,
            SG.TX_PA AS TX_DOWNLOAD_PA,
            L.ID_USER_KEY AS ID_DOWNLOADER_KEY,
            USR.TX_FULL_NAME AS TX_DOWNLOADER_NAME,
            L.DTT_ACTIVITY AS DT_DOWNLOAD,
            L.TX_ACTIVITY_TYPE,
            SD.TX_DOWNLOAD_TYPE,
            SD.TX_INSTITUTION_NAME AS TX_LETTER_ISU_AUTH,
            SD.TX_REMARK,
            SD.TX_REFERRAL_NUMBER AS TX_LETTER_REF_NUM,
            SD.DTT_DOCUMENT_DATE AS DT_LETTER
            FROM T_ACTIVITY_LOG L 
            LEFT JOIN T_SIGNATURE_DOWNLOAD_INFO SD ON SD.ID_SIGNATURE_DOWNLOAD_KEY = L.INT_ON_KEY
            LEFT JOIN T_SIGNATORY SG ON SG.ID_SIGNATORY_KEY = SD.ID_SIGNATORY_KEY
            JOIN T_USER USR ON L.ID_USER_KEY = USR.ID_USER_KEY
            WHERE L.TX_ACTIVITY_TYPE IN ('DOWNLOAD_FULL_SIGANTURE', 'DOWNLOAD_SIGANTURE') ORDER BY L.ID_ACTIVITY_LOG_KEY DESC
        ) V;

