CREATE OR REPLACE VIEW VIEW_ACTIVITY_LOG AS
SELECT ROWNUM AS ID_VIEW_ACTIVITY_KEY, V.* 
FROM (
    SELECT 
        A.ID_USER_KEY, 
        A.TX_ACTIVITY_TYPE, 
        CASE
            WHEN A.TX_ACTIVITY_TYPE = 'VIEW_SIGNATURE' THEN V.TX_NAME
            ELSE U.TX_FULL_NAME
        END AS TX_NAME,
        A.TX_EMAIL AS TX_LINK_SENDING_EMAIL, 
        A.TX_DESC, 
        A.TX_GATEWAY_IP, 
        A.TX_SOURCE_IP,
        A.DTT_ACTIVITY,
        V.DT_CANCEL_EFFECTIVE_DATE, 
        V.DT_CANCEL_TIME, 
        V.DT_INACTIVE_TIME, 
        V.DTT_EFFECTIVE_DATE, 
        V.ID_SIGNATURE_INFO_KEY, 
        V.IS_MAIN_SIGNATURE, 
        V.TX_ADDRESS, 
        V.TX_CANCEL_CAUSE, 
        V.TX_DEPARTMENT, 
        V.TX_DESIGNATION, 
        V.TX_EMAIL AS TX_USER_EMAIL, 
        V.TX_PA, 
        V.TX_REJECTION_CAUSE, 
        V.TX_SIGNATURE_STATUS, 
        V.TX_SIGNATURE_TYPE
    FROM T_ACTIVITY_LOG A
    LEFT JOIN VW_SIGNATURE_INFO V 
        ON V.ID_SIGNATURE_KEY = A.INT_ON_KEY
    LEFT JOIN T_USER U on U.ID_USER_KEY = A.ID_USER_KEY
    UNION ALL
    SELECT  
        L.ID_USER_KEY AS ID_USER_KEY, 
        CASE
            WHEN L.INT_LOGIN = 1 THEN 'LOGIN'
            ELSE 'LOG_OUT' 
        END AS TX_ACTIVITY_TYPE, 
        USR.TX_FULL_NAME AS TX_NAME,
        CAST(NULL AS VARCHAR2(255)) AS TX_LINK_SENDING_EMAIL, 
        CAST(NULL AS VARCHAR2(255)) AS TX_DESC, 
        L.TX_GATEWAY AS TX_GATEWAY_IP, 
        L.TX_IP_ADDR AS TX_SOURCE_IP,
        CASE
            WHEN L.INT_LOGIN = 1 THEN L.DTT_LOGIN_TIME
            ELSE L.DTT_LOGOUT_TIME
        END AS DTT_ACTIVITY,
        CAST(NULL AS DATE) AS DT_CANCEL_EFFECTIVE_DATE, 
        CAST(NULL AS DATE) AS DT_CANCEL_TIME, 
        CAST(NULL AS DATE) AS DT_INACTIVE_TIME, 
        CAST(NULL AS DATE) AS DTT_EFFECTIVE_DATE, 
        CAST(NULL AS NUMBER) AS ID_SIGNATURE_INFO_KEY, 
        CAST(0 AS NUMBER) AS IS_MAIN_SIGNATURE, 
        CAST(NULL AS VARCHAR2(255)) AS TX_ADDRESS, 
        CAST(NULL AS VARCHAR2(255)) AS TX_CANCEL_CAUSE, 
        CAST(NULL AS VARCHAR2(255)) AS TX_DEPARTMENT, 
        USR.TX_DESIGNATION AS TX_DESIGNATION, 
        USR.TX_EMAIL AS TX_USER_EMAIL, 
        CAST(NULL AS VARCHAR2(255)) AS TX_PA, 
        CAST(NULL AS VARCHAR2(255)) AS TX_REJECTION_CAUSE, 
        CAST(NULL AS VARCHAR2(255)) AS TX_SIGNATURE_STATUS, 
        CAST(NULL AS VARCHAR2(255)) AS TX_SIGNATURE_TYPE
    FROM T_LOGIN L
    LEFT JOIN T_USER USR ON USR.ID_USER_KEY = L.ID_USER_KEY        
) V
WHERE NOT (V.ID_USER_KEY IS NULL AND V.TX_ACTIVITY_TYPE IN ('LOGIN', 'LOG_OUT')) AND V.TX_NAME IS NOT NULL
ORDER BY V.DTT_ACTIVITY DESC;