CREATE OR REPLACE VIEW VW_BANK_REPORT AS
SELECT ROWNUM ID_BANK_REPORT_KEY, V.* FROM 
    (
    SELECT 
    SF.ID_INSTITUTION_KEY,
    SF.INT_OWN_INSTITUTION,
    SF.INSTITUTION_NAME,
    SF.TX_EMPLOYEE_ID,
    SF.TX_DELIGATION,
    SF.TX_GROUP,
    SF.TX_BRANCH_NAME,
    SF.TX_NAME,
    SF.TX_DESIGNATION,
    SF.DTT_EFFECTIVE_DATE,
    SF.TX_STATUS
    FROM VW_SIGNATURE_INFO SF
    WHERE SF.IS_ACTIVE = 1 
    AND SF.IS_MAIN_SIGNATURE = 1
    ORDER BY SF.INSTITUTION_NAME ASC
    ) V;