CREATE OR REPLACE VIEW VW_EXCEPTION_REPORT
AS
SELECT ROWNUM AS ID_KEY,
U.TX_LOGIN_NAME AS USER_NAME,B.TX_BRANCH_NAME AS BRUNCH_NAME,
I.TX_NAME  AS INSTITUATION_NAME, U.TX_FULL_NAME AS EMPLOYEE_NAME,
U.TX_EMAIL,U.TX_PHONE_NUMBER,U.TX_NID,U.DTT_DOB, U.INT_ALLOW_LOGIN,
CASE WHEN U.INT_ALLOW_LOGIN=1 AND U.IS_ACTIVE=1 THEN 'ACTIVE' WHEN U.IS_ACTIVE=0 THEN 'DELETE' 
ELSE 'INACTIVE' END AS USER_STATUS,
U.TX_IP_ADDR AS IP_ADDRESS,
L.DTT_LOGIN_TIME AS TX_ATTEMPT_LOGIN,
 L.INT_ATTEMPT_STATUS
 FROM T_USER U 
 LEFT JOIN T_BRANCH B ON U.ID_LEGAL_ENTITY_KEY=B.ID_BRANCH_ID
 LEFT JOIN T_INSTITUTION I ON U.ID_INSTITUTION_KEY = I.ID_INSTITUTION_KEY
 LEFT JOIN T_LOGIN L ON U.TX_LOGIN_NAME = L.TX_LOGIN_NAME AND L.INT_ATTEMPT_STATUS<>1;