CREATE OR REPLACE VIEW VW_INSTITUTION_EXTRA_INFO AS
SELECT ROWNUM AS ID_INSTITUTION_EXTRA_KEY, V.* FROM
  (SELECT 
    I.ID_INSTITUTION_KEY
    ,I.INT_NUMBER_GEN_USER AS "USER_LIMIT"
    ,COUNT(DISTINCT U.ID_USER_KEY) AS "APPROVE_USER"
    ,COUNT(DISTINCT UR.ID_USER_KEY) AS "PEND_USER"
    FROM T_INSTITUTION I
    LEFT JOIN T_USER U ON I.ID_INSTITUTION_KEY = U.ID_INSTITUTION_KEY AND U.TX_USER_STATUS = 'APPROVED' AND U.IS_ACTIVE = 1
    LEFT JOIN T_USER UR ON I.ID_INSTITUTION_KEY = UR.ID_INSTITUTION_KEY AND UR.TX_USER_STATUS = 'PEND_APPROVE' AND U.IS_ACTIVE = 1
    WHERE I.IS_ACTIVE = 1
    GROUP BY
        U.TX_USER_STATUS
        ,I.ID_INSTITUTION_KEY
        ,I.INT_NUMBER_GEN_USER 
        ,UR.ID_USER_KEY
) V;