CREATE OR REPLACE VIEW VW_LOGGED_REPORT
AS
SELECT L.ID_LOGIN_KEY ID_LOGGED_KEY, 
L.TX_LOGIN_NAME, 
CASE WHEN L.INT_ATTEMPT_STATUS = 1 THEN 'SUCCESS' ELSE 'FAIL' END TX_ATTEMPT_STATUS, 
CASE WHEN L.INT_LOGIN = 1 THEN 'LOGIN' ELSE 'LOGOUT' END TX_ACTION,
L.TX_IP_ADDR,
U.TX_EMAIL,
CASE WHEN L.DTT_GEN_NOTICE IS NOT NULL THEN TO_CHAR(L.DTT_GEN_NOTICE, 'DD-MM-YYYY hh24:MI:SS') ELSE '' END TX_GEN_NOTICE_TIME,
CASE WHEN L.DTT_MD_NOTICE IS NOT NULL THEN TO_CHAR(L.DTT_MD_NOTICE, 'DD-MM-YYYY hh24:MI:SS') ELSE '' END TX_MD_NOTICE_TIME,
CASE WHEN L.DTT_MOD_TIME IS NOT NULL THEN TO_CHAR(L.DTT_MOD_TIME, 'DD-MM-YYYY hh24:MI:SS') ELSE '' END TX_MOD_TIME,
CASE WHEN L.DTT_LOGIN_TIME IS NOT NULL THEN TO_CHAR(L.DTT_LOGIN_TIME, 'DD-MM-YYYY hh24:MI:SS') ELSE '' END TX_LOGIN_TIME,
CASE WHEN L.DTT_LOGOUT_TIME IS NOT NULL THEN TO_CHAR(L.DTT_LOGOUT_TIME, 'DD-MM-YYYY hh24:MI:SS') ELSE '' END TX_LOGOUT_TIME,
L.DTT_MOD_TIME,
L.DTT_LOGIN_TIME,
L.DTT_LOGOUT_TIME,
CASE WHEN U.TX_FULL_NAME = '?'  THEN  U.TX_FIRST_NAME ELSE U.TX_FULL_NAME END TX_FULL_NAME,
I.TX_NAME TX_INSTITUTION_NAME,
I.ID_INSTITUTION_KEY,
U.ID_USER_KEY,
L.DTT_ENTRY,
B.TX_BRANCH_NAME
FROM T_LOGIN L 
LEFT JOIN T_USER U ON U.TX_LOGIN_NAME = L.TX_LOGIN_NAME
LEFT JOIN T_INSTITUTION I ON I.ID_INSTITUTION_KEY = U.ID_INSTITUTION_KEY
LEFT JOIN T_BRANCH B ON B.ID_BRANCH_ID=U.ID_LEGAL_ENTITY_KEY
ORDER BY L.ID_LOGIN_KEY DESC;