CREATE OR REPLACE VIEW VW_MANDATORY
 AS
 SELECT I.TX_NAME AS TX_BANK,U.TX_LOGIN_NAME,
 'TEST ROLE ' AS TX_ROLE_NAME,
 U.TX_FULL_NAME,
 U.TX_EMAIL,
 U.TX_PHONE_NUMBER,
 'TEST NID ' AS  TX_NID ,
 TO_CHAR(U.DTT_DOB,'YYYY-MM-DD') AS TX_DATE_OF_BIRTH,
 CASE WHEN U.IS_ACTIVE =1 THEN 'ACTIVE' ELSE 'INACTIVE' END AS USER_STATUS,
 L.DTT_GEN_NOTICE,
 L.DTT_MD_NOTICE,
 L.TX_IP_ADDR
 FROM T_INSTITUTION I JOIN T_USER U
 ON I.ID_USER_CREATE_KEY = U.ID_USER_KEY
 LEFT JOIN T_LOGIN L
 ON L.ID_USER_KEY=U.ID_USER_KEY