CREATE OR REPLACE VIEW VW_NEWS_FEET_OTHERS AS 
SELECT ROWNUM AS id_key, 
	U.TX_LOGIN_NAME AS TX_LOGIN_NAME
	,AL.TX_ACTIVITY_TYPE
	,AL.DTT_ACTIVITY
	,TO_CHAR(AL.DTT_ACTIVITY,'yyyy-mm-dd hh:mi') AS TX_ACTION_TIME
	FROM T_ACTIVITY_LOG  AL, T_USER U 
	WHERE AL.ID_USER_KEY=U.ID_USER_KEY
	AND U.IS_ACTIVE=1
	AND TX_ACTIVITY_TYPE IN('VIEW_NEWS_FEEDS','VIEW_LEGAL_DISCLAMER','VIEW_CONTACT_INFO');