CREATE OR REPLACE VIEW VW_RPT_HR_MODULE AS
SELECT ROWNUM AS ID_HR_MODULE_KEY, V.* FROM
(
    SELECT 
        SG.ID_SIGNATORY_KEY,
        SG.ID_USER_CREATE_KEY AS ID_HR_MAKER_KEY,
        USR.TX_FULL_NAME AS TX_HR_MAKER_NAME,
        SG.ID_AUTHORIZE_BY AS ID_HR_CHECKER_KEY,
        USRC.TX_FULL_NAME AS TX_HR_CHECKER_NAME,
        SG.TX_PA,
        SG.TX_NAME,
        SG.DTT_CREATE AS DT_PA_CREATE,
        FAG.DTT_CREATE AS DT_AGREEMENT_FILE,
        FAP.DTT_CREATE AS DT_APPROVER_FILE,
        FCA.DTT_CREATE AS DT_CANCEL_FILE,
        FCC.DTT_CREATE AS DT_CANCEL_CERCULAR,
        SGR.TX_CANCEL_CAUSE AS TX_CANCEL_CAUSE
        FROM T_SIGNATORY SG
        JOIN T_USER USR ON USR.ID_USER_KEY = SG.ID_USER_CREATE_KEY
        JOIN T_USER USRC ON USRC.ID_USER_KEY = SG.ID_AUTHORIZE_BY
        LEFT JOIN T_FILES FAG ON FAG.ID_OBJECT_KEY = SG.ID_SIGNATORY_KEY AND FAG.TX_OBJECT_TYPE = 'AGREEMENT_FILE'
        LEFT JOIN T_FILES FAP ON FAP.ID_OBJECT_KEY = SG.ID_SIGNATORY_KEY AND FAP.TX_OBJECT_TYPE = 'APPROVAL_FILE'
        LEFT JOIN T_FILES FCA ON FCA.ID_OBJECT_KEY = SG.ID_SIGNATORY_KEY AND FCA.TX_OBJECT_TYPE = 'CANCELATION_APPROVAL'
        LEFT JOIN T_FILES FCC ON FCC.ID_OBJECT_KEY = SG.ID_SIGNATORY_KEY AND FCC.TX_OBJECT_TYPE = 'CANCELATION'
        JOIN T_INSTITUTION INS ON INS.ID_INSTITUTION_KEY = SG.ID_INSTITUTION_KEY AND INS.INT_OWN_INSTITUTION = 1
        LEFT JOIN T_SIGNATURE SGR ON SGR.ID_SIGNATORY_KEY = SG.ID_SIGNATORY_KEY AND SGR.IS_MAIN_SIGNATURE = 1
        WHERE SG.TX_STATUS = 'APPROVED' AND SG.ID_INSTITUTION_KEY = USR.ID_INSTITUTION_KEY
        ORDER BY SG.ID_SIGNATORY_KEY DESC
        ) V;