CREATE OR REPLACE VIEW VW_REQUEST AS
  SELECT R.ID_REQUEST_KEY AS ID_EXTERNAL_USER_REQUEST_KEY,
  R.ID_USER_CREATE_KEY, 
  U.TX_PROFILE AS TX_IMAGE,
  R.DT_COMPLETE, 
  R.INT_SIGNATORY_KEY, 
  R.TX_DESCRIPTION,
  R.TX_STATUS AS TX_REQUEST_STATUS, 
  R.DTT_CREATE AS TX_REQUEST_TIME, 
  R.DTT_MOD,
  R.TX_TYPE AS TX_REQUEST_TYPE,
  R.TX_USER_REQ_TYPE, 
  R.TX_USER_REQ_FORM,
  --R.TX_REJECT_CAUSE,
  S.TX_EMAIL, 
  S.TX_NAME, 
  S.TX_PA, 
  S.TX_DEPARTMENT, 
  S.TX_DESIGNATION,
  U.TX_EMAIL AS TX_REQUESTER_EMAIL, 
  U.TX_FULL_NAME AS TX_REQUESTER_NAME, 
  (
    SELECT USR.TX_LOGIN_NAME FROM T_USER USR
    WHERE USR.ID_USER_KEY = R.ID_COMPLETE_BY
  ) AS TX_COMPLETE_BY,
  I.TX_NAME AS TX_INSTITUTION_NAME, 
  I.ID_INSTITUTION_KEY , 
  P.TX_LINK_TYPE AS TX_PUBLIC_LINK_TYPE,
  P.TX_SENDING_EMAIL AS TX_PUBLIC_LINK_SEND,
  P.IS_VIEW_LINK AS INT_VIEW_PUBLIK_LINK,
  P.TX_PUBLIC_LINK AS TX_LINK,
  P.DT_START AS DT_FROM_DATE,
  P.DT_EXPIRE AS DT_TO_DATE,
  II.TX_NAME AS TX_REQ_USR_INS_NAME,   
  RU.TX_FIRST_NAME AS TX_REJECTED_BY,
  R.TX_REJECT_CAUSE,CHECKER.TX_FULL_NAME as tx_checked_by,
  APPROVE.TX_FULL_NAME as tx_COMPLETED_BY,
  R.DT_CHECKER AS CHECKER_DATE,
  R.DT_COMPLETE_REQUEST AS COMPLETE_DATE
  FROM T_REQUEST R
  LEFT JOIN T_SIGNATORY S on R.INT_SIGNATORY_KEY = S.ID_SIGNATORY_KEY 
  JOIN T_USER U on R.ID_USER_CREATE_KEY = U.ID_USER_KEY
  JOIN T_INSTITUTION I on U.ID_INSTITUTION_KEY = I.ID_INSTITUTION_KEY
  LEFT JOIN T_PUBLIC_LINK P on P.ID_REQUEST_KEY = r.ID_REQUEST_KEY
  LEFT JOIN T_INSTITUTION II on U.ID_INSTITUTION_KEY = II.ID_INSTITUTION_KEY
  LEFT JOIN T_USER RU ON R.ID_REJECT_BY = RU.ID_USER_KEY
  LEFT JOIN T_USER CHECKER ON R.ID_CHECKER_BY = CHECKER.ID_USER_KEY ---need add
LEFT JOIN T_USER APPROVE ON R.ID_COMPLETE_BY = APPROVE.ID_USER_KEY --need add
  WHERE R.IS_ACTIVE = 1
ORDER BY R.DTT_MOD DESC;