CREATE OR REPLACE VIEW VW_RPT_SINGATURE_DOWNLOAD
AS
select l.ID_ACTIVITY_LOG_KEY ID_KEY, 
TO_CHAR(l.DTT_ACTIVITY, 'DD-MM-YYYY hh24:MM:SS') TX_ACTIVITY_TIME,
L.DTT_ACTIVITY,
l.TX_ACTIVITY_TYPE,
l.TX_DESC,
l.TX_EMAIL, 
l.TX_GATEWAY_IP,
l.TX_SOURCE_IP,
l.tx_pa,
l.tx_name TX_HOLDER_NAME,
CASE WHEN u.TX_FULL_NAME = '?'  THEN  u.TX_FIRST_NAME ELSE u.TX_FULL_NAME end TX_FULL_NAME,
i.TX_NAME TX_INSTITUTION_NAME,
i.ID_INSTITUTION_KEY
from T_ACTIVITY_LOG l
left join t_user u on  u.ID_USER_KEY = l.ID_USER_KEY
join t_institution i on i.ID_INSTITUTION_KEY = u.ID_INSTITUTION_KEY
WHERE l.TX_ACTIVITY_TYPE IN('SINGLE_DOWNLOAD', 'BOOKLET_DOWNLOAD')
ORDER BY l.ID_ACTIVITY_LOG_KEY DESC
