CREATE OR REPLACE VIEW VW_SIGNATURE_INFO AS
SELECT ROWNUM AS ID_SIGNATURE_INFO_KEY, V.* FROM
    (
        SELECT 
            SRY.ID_INSTITUTION_KEY,
            SRY.TX_EMPLOYEE_ID,
            INS.TX_NAME AS INSTITUTION_NAME,
            SRY.TX_PA,
            SRY.TX_NAME,
            SRY.TX_CONTACT_NUMBER,
            SRY.DT_BIRTHDAY,
            SRY.TX_BRANCH_NAME,
            SRY.TX_EMAIL,
            SRY.TX_DEPARTMENT,
            SRY.TX_DESIGNATION,
            SRY.TX_ADDRESS,
            SRY.TX_APPROVAL,
            SRY.IS_ACTIVE AS IS_SIGNATORY_ACTIVE,
            SRE.IS_ACTIVE AS IS_SIGNATURE_ACTIVE,
            SRE.DTT_CREATE AS DTT_SIGNATURE_CREATE,
            SRE.ID_SIGNATURE_KEY,
            SRE.ID_SIGNATORY_KEY,
            SRE.DTT_EFFECTIVE_DATE,
            --SRE.TX_SIGNATURE_PATH,
            REGEXP_SUBSTR(SRE.TX_SIGNATURE_PATH, '[^\\]+$', 1, 1) AS TX_SIGNATURE_PATH,
            SRE.TX_SIGNATURE_STATUS,
            SRE.TX_STATUS,
            SRE.TX_REJECTION_CAUSE,
            SRE.TX_CANCEL_CAUSE,
            SRE.DT_CANCEL_TIME,
            SRE.IS_ACTIVE,
            SRE.DT_CANCEL_EFFECTIVE_DATE,
            SRE.DT_INACTIVE_TIME,
            SRE.TX_REMARKS,
            SRE.IS_MAIN_SIGNATURE,
            SRE.DTT_MOD,
            SRE.TX_SIGNATURE_TYPE,
            SRE.id_approved_by_id AS ID_APPROVE_BY,
            SRE.dtt_approve AS DT_APPROVE_DATE,
            SRE.ID_AUTH_BY,
            SRE.DT_AUTH_DATE,
            SRY.TX_DELIGATION,
            SRY.TX_GROUP,
            INS.INT_OWN_INSTITUTION,
            SRY.ID_APPROVE_BY AS ID_PA_APPROVE_BY,
            SRY.DT_APPROVE_TIME AS DT_PA_APPROVE_DATE,
            SRY.ID_AUTHORIZE_BY AS ID_PA_AUTH_BY,
            SRY.DT_AUTHORIZE_TIME AS DT_PA_AUTH_DATE,
            SRY.TX_NID,
            FAG.DTT_CREATE AS DTT_AGREEMENT_FILE,
            FAP.DTT_CREATE AS DTT_APPROVAL_FILE,
            CASE WHEN SRE.IS_ACTIVE = 0 THEN SRE.DTT_MOD END AS DTT_DELETE
        FROM T_SIGNATORY SRY
        JOIN T_SIGNATURE SRE ON SRY.ID_SIGNATORY_KEY = SRE.ID_SIGNATORY_KEY
        JOIN T_INSTITUTION INS ON SRY.ID_INSTITUTION_KEY = INS.ID_INSTITUTION_KEY AND INS.IS_ACTIVE = 1
        LEFT JOIN T_FILES FAG ON FAG.ID_OBJECT_KEY = SRY.ID_SIGNATORY_KEY
            AND FAG.TX_OBJECT_TYPE = 'AGREEMENT_FILE'
        LEFT JOIN T_FILES FAP ON FAP.ID_OBJECT_KEY = SRY.ID_SIGNATORY_KEY
            AND FAP.TX_OBJECT_TYPE = 'APPROVAL_FILE'
        WHERE SRY.ID_SIGNATORY_KEY = SRE.ID_SIGNATORY_KEY
        AND SRY.ID_INSTITUTION_KEY = INS.ID_INSTITUTION_KEY
        AND SRY.TX_STATUS = 'APPROVED'
        AND SRY.IS_ACTIVE = 1
        ORDER BY SRE.DTT_CREATE DESC
    ) V;
