CREATE OR REPLACE VIEW VW_USER_AUDIT_LIST
AS
    SELECT U.*,
           CASE
               WHEN U.TX_USER_TYPE = 'INTERNAL_USER' THEN B.TX_BRANCH_NAME
               ELSE U.TX_EXT_BRANCH_NAME
           END                 TX_BRANCH_NAME,
           I.TX_NAME           AS TX_INSTITUATION_NAME,
           C.VALUE1            AS TX_DEPARTMENT,
           TUM.TX_FULL_NAME    AS TX_MAKER_NAME,
           TUC.TX_FULL_NAME    AS TX_CHECKER_NAME,
           TUU.TX_FULL_NAME    AS TX_MODIFIER_NAME
      FROM T_USER_AUDIT  U
           LEFT JOIN T_BRANCH B ON U.ID_LEGAL_ENTITY_KEY = B.ID_BRANCH_ID
           LEFT JOIN T_INSTITUTION I
               ON I.ID_INSTITUTION_KEY = U.ID_INSTITUTION_KEY
           LEFT JOIN T_CONFIGURATION C
               ON     C.CONFIG_ID = U.ID_DEPARTMENT
                  AND C.CONFIG_SUB_GROUP = 'DEPARTMENT'
           LEFT JOIN T_USER TUM ON U.ID_USER_CREATE_KEY = TUM.ID_USER_KEY
           LEFT JOIN T_USER TUC ON U.ID_APPROVED_BY_ID = TUC.ID_USER_KEY
           LEFT JOIN T_USER TUU ON U.ID_USER_MOD_KEY = TUU.ID_USER_KEY