CREATE OR REPLACE VIEW VW_USER_PERMISSION AS
SELECT ROWNUM ID, V.* FROM (
SELECT DN.ID_PERMISSION_KEY, DN.TX_PERMISSION_NAME, DN.TX_DISPLAY_NAME PERMISSION_DIS_NAME,
U.ID_USER_KEY,U.TX_LOGIN_NAME,R.ID_ROLE_KEY, R.TX_ROLE_NAME, R.TX_DISPLAY_NAME RL_DIS_NAME
FROM T_USER U
JOIN T_GENERIC_MAP RM ON U.ID_USER_KEY = RM.LNG_FROM_ID  AND RM.IS_ACTIVE=1 AND RM.TX_FROM_TYPE_NAME='USER'
AND RM.TX_STATUS='APPROVED' AND RM.TX_TO_TYPE_NAME = 'ROLE' 
JOIN T_GENERIC_MAP AP ON RM.LNG_TO_ID=AP.LNG_TO_ID AND AP.TX_TO_TYPE_NAME='ROLE' AND AP.TX_STATUS='APPROVED' 
AND AP.TX_FROM_TYPE_NAME='APP_PERMISSION' AND AP.IS_ACTIVE=1
JOIN T_APP_PERMISSION DN ON AP.LNG_FROM_ID=DN.ID_PERMISSION_KEY AND DN.IS_ACTIVE=1
JOIN T_ROLE R ON R.ID_ROLE_KEY=RM.LNG_TO_ID AND R.IS_ACTIVE=1
WHERE U.TX_LOGIN_NAME != 'softcafe'
UNION ALL
    select P.ID_PERMISSION_KEY, P.TX_PERMISSION_NAME, P.TX_DISPLAY_NAME PERMISSION_DIS_NAME, U.ID_USER_KEY , 
    U.TX_LOGIN_NAME, 1 AS ID_ROLE_KEY, 'SUPER_ADMIN' AS TX_ROLE_NAME,'SUPER ADMIN' AS RL_DIS_NAME
    FROM T_APP_PERMISSION P
    LEFT JOIN T_USER U ON U.TX_LOGIN_NAME = 'softcafe'
    WHERE P.IS_ACTIVE = 1) V;