export enum ActivityType{
    VIEW_SIGNATURE = "VIEW_SIGNATURE",
    DOWNLOAD_SIGANTURE = "DOWNLOAD_SIGANTURE",
    CHANGE_PASSWORD = "CHANGE_PASSWORD",
    FORGOT_PASSWORD = "FORGOT_PASSWORD",
    SIGNATURE_VIEWER = "SIGNATURE_VIEWER"
}