package com.softcafe.esignature.model;

public enum MailType {
	INTERNAL_USER_CHECK, EXTERNAL_USER_CHECK,
	INTERNAL_INACTIVATION_CHECK, EXTERNAL_INACTIVATION_CHECK, INTERNAL_ACTIVATION_CHECK, EXTERNAL_ACTIVATION_CHECK,
	SIGNATURE_CHECK, CANCEL_CHECK, INACTIVATION_CHECK, PA_CHECK, BOOKLET_CHECK, BOOKLET_REJECT,
	VERIFY_SIGNATURE_CHECK, VERIFY_SIGNATURE_REJECT, GENERATE_LINK_CHECK, GENERATE_LINK_REJECT, OTHERS_CHECK,
	OTHERS_REJECT, USER_CREATION_CHECK, USER_CREATION_REJECT, USER_ACTIVATION_CHECK,FORGOT_PASSWORD,
	FIRST_LOGING_FIRST_MAIL,FIRST_LOGING_SECOUND_MAIL,RESEND_PASSWORD, USER_ACTIVATION_REJECT,
	USER_DEACTIVATION_CHECK, USER_DEACTIVATION_REJECT, SERVICE_REQUEST_CHECK, SERVICE_REQUEST_REJECT, 
	PASSWORD_CHANGE_SUCCESS, PA_APPLICATION_ADMIN, USER_LOGIN, LOGING_NOTIFY_TEN, LOGING_NOTIFY_SEVEN,
	PASS_NOTIFY_TEN, PASS_NOTIFY_SEVEN, PASSWORD_CHANGE_INFO, UPLOAD_APPROVAL, UPLOAD_AGREEMENT, 
	UPLOAD_CANCELATION, UPLOAD_CANCELATION_APPROVAL, SIGNATURE_UPDATE_CHECK, UPLOAD_UPDATE_APPROVAL,
	UPLOAD_UPDATE_CANCELATION_APPROVAL, UPLOAD_UPDATE_CANCELATION, UPLOAD_UPDATE_AGREEMENT, DELETE_CHECK, 
	UPLOAD_UPDATE_SIGNATURE_AGREEMENT, UPLOAD_UPDATE_SIGNATURE_APPROVAL, UPLOAD_UPDATE_SIGNATURE_CANCELATION, 
	INACTIVATION_UPDATE_CHECK, SND_INACTIVATION_CHECK, SND_SIGNATURE_CHECK, CANCEL_UPDATE_CHECK, SND_CANCEL_CHECK, 
	FULL_SIGNATURE, SINGLE_SIGNATURE, BLOCK_BY_WRONG_PASS, LOGIN_OTP, REJECT_MAIL, PA_REJECT, USER_REJECT
}
