package com.softcafe.esignature.utils;

public enum ActivityType {
	
	VIEW_SIGNATURE,
	VIEW_LEGAL_DISCLAMER,
	DOWNLOAD_SIGANTURE, 
	LOGIN, 
	LOG_OUT, 
	CHANGE_PASSWORD, 
	FORGOT_PASSWORD, 
	USER_ACITVE_MAKE,
	USER_ACITVE_CHECK,
	USER_INACITVE_MAKE, 
	USER_INACITVE_CHECKE,
	SEARCH_SIGNATURE, 
	DOWNLOAD_FULL_SIGANTURE, 
	VIEW_NEWS_FEEDS,
	VIEW_CONTACT_INFO, 
	SAVE_SIGNATORY, 
	UPDATE_SIGNATORY, 
	SAVE_SIGNATURE,
	UPDATE_SIGNATURE, 
	SAVE_AGREEMENT_FILE, 
	SAVE_APPROVAL_FILE, 
	SAVE_OTHER_FILE, 
	SAVE_CANCELATION_APPROVAL_FILE, 
	SAVE_CANCELATION_FILE, 
	PEND_DELETE_SIGNATURE, 
	APPROVE_DELETE_SIGNATURE

}
