package com.softcafe.core.util;

public enum AppPermissionEnum {

	USER_VIEWER, USER_MAKER, USER_APPROVER, DELETE_USER, PASSWORD_ADMIN, VIEW_BRANCH, SAVE_BRANCH, DELETE_BRANCH,
	APPROVE_BRANCH, VIEW_ROLE, MAKE_ROLE, APPROVE_ROLE, DELETE_ROLE, DISCLAIMER_SETUP, APPLICATION_SETUP_MAKER,
	ACCESS_APPLICATION_SETUP, APPLICATION_CONFIG_SETUP, SAVE_PERMISSION, VIEW_PERMISSION, SIGNATURE_MAKER,
	UPDATE_SIGNATURE, UPLOAD_SIGNATURE, FILE_UPLOAD, APPROVE_SIGNATURE, SIGNATURE_DELETER, APPROVE_DELETE_SIGNATURE,
	SIGNATURE_VIEWER, EXTERNAL_SIGNATURE_VERIFIER, INTERNAL_SIGNATURE_VERIFIER, DOWNLOAD_SIGNATURE,
	DOWNLOAD_SINGLE_SIGNATURE, SEARCH_SIGNATURE, REQUEST_MAKER, REQUEST_VIEWER, REQUEST_CHECKER, REQUEST_APPROVER,
	SIGNATORY_MAKER, SIGNATORY_VIEWER, SIGNATORY_CHECKER, INSTITUTION_VIEWER, INSTITUTION_MAKER, INSTITUTION_CHECKER,
	INSTITUTION_DELETER, INSTITUTION_DELETE_APPROVER, MAIL_TEMPLATE_VIEWER, MAIL_TEMPLATE_MAKER, MAIL_TEMPLATE_DELETER,
	MAIL_TEMPLATE_CHECKER, MAIL_TEMPLATE_APPROVER, COPY_TEXT, SIGNATORY_DELETER, AGREEMENT_SETUP_VIEWER,
	AGREEMENT_SETUP_MAKER, SIGNATURE_SETUP_VIEWER, ACTIVITY_LOG_VIEWER, LEGAL_DISCLAIMER_VIEWER, LEGAL_DISCLAIMER_MAKER,
	USER_MANAGMENT, SIGNATURE_LOG_VIEWER, GENERATE_LINK, USER_REPORT_VIEWER, LOGGED_REPORT_VIEWER,
	PASSWORD_REPORT_VIEWER, SIGNATURE_REPORT_VIEWER, SIGNATURE_SEARCH_VIEWER, NEWS_FEED_REPORT_VIEWER,
	PRINT_DOWNLOAD_REPORT_VIEWER, HR_MODULE_REPORT_VIEWER, SIGNATURE_HISTORY_VIEWER, REQUEST_ADMIN, VIEW_DASHBOARD,
	SAMPLE_DOCUMENT_SAVER, SAMPLE_DOCUMENT_DOWNLOADER, VIEW_SECURITY_QUESTION, ADD_SECURITY_QUESTION,
	VIEW_SECURITY_QUESTION_ANS, ADD_SECURITY_QUESTION_ANS, HR_SIGNATURE_CHECKER, USERS_UNDER_ROLE_VIEWER,
	OTHERS_SIGNATURE_UPLOADER, PA_REPORT_VIEWER, BANK_REPORT_VIEWER, HR_ROLE, DOC_REPORT_VIEWER,
	SIGNATURE_HIS_REPORT_VIEWER, EXCEPTION_REPORT_VIEWER,EXTERNAL_SAVE_USER,INTERNAL_SAVE_USER,APPLICATION_CONTACT_SETUP;

}
