package com.softcafe.constants;

public enum ActionType {

	ACTION_NEW("NEW"),
	PASSWORD_ENCREPT("PASSWORD_ENCREPT"),
	SEND_EMAIL("SEND_EMAIL"),
	USER_AUDIT_LOG("USER_AUDIT_LOG"),
	
	PBL_DASHBOARD("PBL_DASHBOARD"),
	DBL_DASHBOARD("DBL_DASHBOARD"),
	FILE_COUNT("FILE_COUNT"),
	APPROVE_USER("APPROVE_USER"),
	business_exec("business_exec"),
	
	LOAD_USER_TYPE_WISE("LOAD_USER_TYPE_WISE"),

    ACTION_TAGGED_WITH_CUSTOMER("TAGGED_WITH_CUSTOMER"),
    
	ACTION_VALUE_CONFIG_NEW("VALUE_CONFIG_NEW"),

	ACTION_VALUE_CONFIG_UPDATE("VALUE_CONFIG_UPDATE"),

	ACTION_VALUE_CONFIG_SELECT("VALUE_CONFIG_SELECT"),

	ACTION_VALUE_CONFIG_DELETE("VALUE_CONFIG_DELETE"),
	
	ACTION_NOMANPLATURE_WISE_SELECT("ACTION_NOMANPLATURE_WISE_SELECT"),
	
	ACTION_SELECT("SELECT"),
	ACTION_LOGON_REPORT("ACTION_LOGON_REPORT"),
	ACTION_SIG_SEARCH_REPORT("ACTION_SIG_SEARCH_REPORT"),
	ACTION_DOWNLOAD_REPORT("ACTION_DOWNLOAD_REPORT"),
	ACTION_SELECT_RESEND("ACTION_SELECT_RESEND"),
	SEARCH("SEARCH"),
	ACTION_SELECTV2("SELECTV2"),
	ACTION_SAVE("SAVE"),
	SAVE_APPLICATION_SETUP("SAVE_APPLICATION_SETUP"),
	SELECT_ROLE_WITH_PERMISSION("SELECT_ROLE_WITH_PERMISSION"),
	SELECT_BY_TYPE("SELECT_BY_TYPE"),
	SELECT_BY_TYPE_STATUS("SELECT_BY_TYPE_STATUS"),
	ACTION_RAW_MT("ACTION_RAW_MT"),
	EXCEPTION_RAW_MESSAGE("EXCEPTION_RAW_MESSAGE"),
	RAW_MESSAGE("RAW_MESSAGE"),
	ACTION_SELECT_AMMUNITION_TYPE("ACTION_SELECT_AMMUNITION_TYPE"),
	MANAGE_ROLE_PERMISSION("MANAGE_ROLE_PERMISSION"),
	
	
	ACTION_SELECT_SINGLE("SELECT_SINGLE"),
	APPROVE("APPROVE"),
	SELECT_GROUP_USERS("SELECT_GROUP_USERS"),
	SELECT_GROUP_CUSTOMER("SELECT_GROUP_CUSTOMER"),
	SELECT_ROLE_GROUP_LIST("SELECT_ROLE_GROUP_LIST"),
	SELECT_GROUP_MT("SELECT_GROUP_MT"),
	SELECT_UNMAPED_GROUP_USERS("SELECT_UNMAPED_GROUP_USERS"),
	SELECT_UNMAPED_GROUP_MT("SELECT_UNMAPED_GROUP_MT"),
	MAP("MAP"),
	MAP_NEW("MAP_NEW"),
	UNMAP_ONE("UNMAP_ONE"),
	REMOVE_SELECTED_GROUP_CUSTOMER("REMOVE_SELECTED_GROUP_CUSTOMER"),
	ACTION_SEARCH("SEARCH"),

	ACTION_SELECT_1("SELECT_1"),
	SELECT_BY_AMMO_TYPE ("SELECT_BY_AMMO_TYPE"),

	ACTION_SELECT_2("SELECT_2"),

	ACTION_SELECT_3("SELECT_3"),
	
	ACTION_SELECT_APPROVE("ACTION_SELECT_APPROVE"),
	
	ACTION_SELECT_2_EXPLOSIVE_TYPE("ACTION_SELECT_2_EXPLOSIVE_TYPE"),

	ACTION_SELECT_2_ROUND_TYPE("ACTION_SELECT_2_ROUND_TYPE"),
	ACTION_ITEM_WISE_SELECT("ACTION_ITEM_WISE_SELECT"),

	SELECT_2_TYPE_OF_AMMUNITION_SAFETY_DISTANCE("SELECT_2_TYPE_OF_AMMUNITION_SAFETY_DISTANCE"),

	SELECT_SEARCH("SELECT_SEARCH"),

	SEARCH_BY_TEXT("SEARCH_BY_TEXT"),

	SEARCH_OR_DATA_FOR_LIST("SEARCH_OR_DATA_FOR_LIST"),
	LOAD_AMMO_TYPE_GROUP("LOAD_AMMO_TYPE_GROUP"),
	

	SEARCH_AMMUNATION_DATA_FOR_LIST("SEARCH_AMMUNATION_DATA_FOR_LIST"),

	SEARCH_AMMUNATION_DATA("SEARCH_AMMUNATION_DATA"),
	SEARCH_DATA_FOR_AMMO_REPORT("SEARCH_DATA_FOR_AMMO_REPORT"),

	AMMUNATION_SEARCH_DATA_REPORT("AMMUNATION_SEARCH_DATA_REPORT"),

	SEARCH_DATA_FOR_LIST_PDF("SEARCH_DATA_FOR_LIST_PDF"),

	SEARCH_DATA_FOR_NEQ_CALCULATION("SEARCH_DATA_FOR_NEQ_CALCULATION"),

	ACTION_SELECT_ALL_HAVE_AMMO_TYPE_ID("SELECT_ALL_HAVE_AMMO_TYPE_ID"),
	ACTION_SELECT_ALL_NOMANCLATURE("ACTION_SELECT_ALL_NOMANCLATURE"),
	

	EXCEL_EXPORT("EXCEL_EXPORT"),

	SELECT_SINGLE("SELECT_SINGLE"),

	ACTION_SELECT_ALL("SELECT_ALL"),

	INACTIVE_ALL("INACTIVE_ALL"),

	ACTION_DELETE("DELETE"),
	IS_ASSIGN_ROLE("IS_ASSIGN_ROLE"),
	ACTION_APPROVE("APPROVE"),
	LOAD_PERMISSION("LOAD_PERMISSION"),
	
	
	CUSTOMER_APPROVE("CUSTOMER_APPROVE"),

	ACTION_INCIDENT_COUNT("INCIDENT_COUNT"),

	ACTION_MANAGE_ROLE("MANAGE_ROLE"),
	ACTION_MANAGE_ROLE_GROUP("MANAGE_ROLE_GROUP"),
	
	MANAGE_ROLE_GROUP("MANAGE_ROLE_GROUP"),
	
	ACTION_MANAGE_USER_APP("MANAGE_APP"),
	
	

	ACTION_SELECT_SINGLE_WITH_ROLE("SELECT_SINGLE_WITH_ROLE"),
	SELECT_SINGLE_WITH_ROLE_GROUP("SELECT_SINGLE_WITH_ROLE_GROUP"),
	SELECT_USER_APP("SELECT_USER_APP"),
	REGISTER("REGISTER"),
	
	

	ACTION_UPDATE("UPDATE"),
	ACTION_UPDATE_2("UPDATE_2"),
	

	ACTION_LOGIN("LOGIN"),

	ACTION_LOGOUT("LOGOUT"),

	ACTION_RESET_PASS("RESET_PASS"),

	ACTION_CHANGE_PASS("CHANGE_PASS"),

	ACTION_FORGOT_PASS("FORGOT_PASS"),

	ACTION_AUTH_FORGOT_PASS("AUTH_FORGOT_PASS"),

	ACTION_SELECT_USER_ROLE("SELECT_USER_ROLE"),

	ACTION_ALL_OVERVIEW("ALL_OVERVIEW"),

	ACTION_TOGGLE_ACTIVATION("TOGGLE_ACTIVATION"),

	ACTION_TOGGLE_2_FA("TOGGLE_2_FA"),
	ACTION_SELECT_USER_ALL_APP("SELECT_USER_ALL_APP"),

	ACTION_VERIFY_LOGIN_2_FA("VERIFY_LOGIN_2_FA"),

	ACTION_RESEND_2FA_CODE("RESEND_2FA_CODE"),

	ACTION_LOAD_LOCATION("LOAD_LOCATION"),

	SEARCH_LOADTABLE_DATA_FOR_LIST("SEARCH_LOADTABLE_DATA_FOR_LIST"),

	SEARCH_LOADTABLE_DATA("SEARCH_LOADTABLE_DATA"),

	LOADTABLE_SEARCH_DATA_REPORT("LOADTABLE_SEARCH_DATA_REPORT"),
	BRUNCH_LIST("BRUNCH_LIST"),
	STATE_LIST("STATE_LIST"),
	
	DELETE_MULTI_BANK_NAME("DELETE_MULTI_BANK_NAME"), // Al-Amin
	UPDATE_MULTI_BANK_NAME("UPDATE_MULTI_BANK_NAME"), // Al-Amin
	
	SELECT_ALL_ITEM_NO("SELECT_ALL_ITEM_NO"), 
	SELECT_PERMISSION_ROLE("SELECT_PERMISSION_ROLE"), 
	MANAGE_APP_PERMISSION("MANAGE_APP_PERMISSION"), 
	PEND_MAIL_DETAILS("PEND_MAIL_DETAILS"), 
	APPROVE_ROLE("APPROVE_ROLE"),
	APPROVE_DEASSIGN("APPROVE_DEASSIGN"),
	APPROVE_PERMISSION("APPROVE_PERMISSION"),
	APPROVE_DEASSIGN_PERMISSION("APPROVE_DEASSIGN_PERMISSION"),
	SAVE_QUESTION_ANS("SAVE_QUESTION_ANS"),
	SELECT_ALL_ANS("SELECT_ALL_ANS"),
	SEARCH_PA("SEARCH_PA"),
	REQUEST4LINK("REQUEST4LINK"), 
	SEARCH_NAME("SEARCH_NAME"), 
	ACTION_SELECT_ALL_UPLOAD("ACTION_SELECT_ALL_UPLOAD"),
	LOAD_IMAGE("LOAD_IMAGE"),
	LOAD_DETAILS("LOAD_DETAILS"), 
	CHECK_MASTER_USER("CHECK_MASTER_USER"), 
	DOWNLOAD_FILE("DOWNLOAD_FILE"), 
	SELECT_BY_USER("SELECT_BY_USER"), 
	VIEW_REQUEST("VIEW_REQUEST"), 
	SEARCH_PA_NAME("SEARCH_PA_NAME"), 
	LDAP_LOGIN_NAME_CHECK("LDAP_LOGIN_NAME_CHECK"),
	SELECT_ALL_WITHOUT_PRIME("SELECT_ALL_WITHOUT_PRIME"),
	FIND_LINK("FIND_LINK"),
	CHECK_USER("CHECK_USER"),
	SELECT_ALL_AGREEMENT("SELECT_ALL_AGREEMENT"), 
	BUILD_IMAGE64("BUILD_IMAGE64"),
	SAVE_SIG_VIEW_SETUP("SAVE_SIG_VIEW_SETUP"),
	SELECT_ALL_VIEW_SETUP("SELECT_ALL_VIEW_SETUP"),
	SELECT_ALL_INFO("SELECT_ALL_INFO"), 
	SAVE_NEW_PASS("SAVE_NEW_PASS"), 
	SELECT_ALL_LEGAL("SELECT_ALL_LEGAL"), 
	SELECT_SAMPLE_DOC("SELECT_SAMPLE_DOC"), 
	ACTION_DELETE_AGREEMENT("DELETE_AGREEMENT"), 
	SAVE_APP_CONFIG("SAVE_APP_CONFIG"), 
	SELECT_ALL_APP_CONFIG("SELECT_ALL_APP_CONFIG"), 
	SELECT_ALL_APP_AD_INFO("SELECT_ALL_APP_AD_INFO"), 
	SELECT_ALL_LAST_USER_CONFIG("LAST_USER_CONFIG"), 
	FIRST_ACCEPT("FIRST_ACCEPT"), 
	SECOUND_ACCEPT("SECOUND_ACCEPT"), 
	LOAD_EXTRA("LOAD_EXTRA"),
	SELECT_ALL_INSTUTION("ALL_INSTUTION"), 
	SELECT_BY_OTP("SELECT_BY_OTP"), 
	RESET_PASSWORD("RESET_PASSWORD"), 
	USER_ACTIVATION("USER_ACTIVATION"), 
	SUBMIT("SUBMIT"), 
	SEARCH_HISTORY("SEARCH_HISTORY"), 
	SELECT_VIEW_SETUP("SELECT_VIEW_SETUP"), 
	ACTION_REJECT("REJECT"), 
	SEARCH_SIGNATURE("SEARCH_SIGNATURE"),
	SEARCH2("SEARCH2"), 
	SEARCH_SIGNATORY("SEARCH_SIGNATORY"), 
	SEARCH_EMP_ID("SEARCH_EMP_ID"),
	SEARCH_PA_EMP("SEARCH_PA_EMP"), 
	SEARCH_EX_INSTITUTION("SEARCH_EX_INSTITUTION"), 
	DELETE_SAMPLE_DOC("DELETE_SAMPLE_DOC"),
	SELECT_CONTACT_INFO("SELECT_CONTACT_INFO"), 
	ACTION_USER_SEARCH_REPORT("ACTION_USER_SEARCH_REPORT"), 
	ACTION_PEND_DELETE("PEND_DELETE"),
	ACTION_PASSWORD_SEARCH_REPORT("ACTION_PASSWORD_SEARCH_REPORT"),
	ACTION_NEWS_FEED_OTHERS_REPORT("ACTION_NEWS_FEED_OTHERS_REPORT"), 
	SELECT_ALL_CONTACT_INFO("SELECT_ALL_CONTACT_INFO"),
	SEARCH_PA_NAME_HISTOTY("SEARCH_PA_NAME_HISTOTY"), 
	FIND_USER_BY_ROLE("FIND_USER_BY_ROLE"), 
	ACTION_PA_SEARCH_REPORT("ACTION_PA_SEARCH_REPORT"), 
	ACTION_BANK_SEARCH_REPORT("ACTION_BANK_SEARCH_REPORT"), 
	ACTION_SIG_SEARCH_REPORT2("ACTION_SIG_SEARCH_REPORT2"), 
	SEARCH_FOR_DOWN("SEARCH_FOR_DOWN"), 
	SEARCH24DOWN("SEARCH24DOWN"), 
	ACTION_HR_MODULE_SEARCH_REPORT("ACTION_HR_MODULE_SEARCH_REPORT"), 
	CHECK_PASS("CHECK_PASS"),
	ACTION_SIG_HISTORY("ACTION_SIG_HISTORY"), 
	ACTION_DOC_REPORT("ACTION_DOC_REPORT"), 
	ACTION_EXCEPTION_REPORT("ACTION_EXCEPTION_REPORT"), 
	LOGIN_OTP("LOGIN_OTP"),
	SELECT_ALL_CHARACTER_MAX_LENGTH("SELECT_ALL_CHARACTER_MAX_LENGTH"), 
	SELECT_MAX_LENGTH_INFO("SELECT_MAX_LENGTH_INFO"), 
	APPROVE_SAMPLE_DOC("APPROVE_SAMPLE_DOC"), 
	SELECT_PEND_USER("SELECT_PEND_USER"),
	SELECT_ALL_ROLE("SELECT_ALL_ROLE"), 
	UNLOCK_INTERNAL_USER("UNLOCK_INTERNAL_USER"), 
	INTERNAL_USER_UNLOCK_OTP("INTERNAL_USER_UNLOCK_OTP"), 
	SELECT_ALL_4CHECKER("SELECT_ALL_4CHECKER"), 
	USER_REGECT("USER_REGECT"), 
	USER_CLOSE("USER_CLOSE"),
	ACTIVITY_LOG_SEARCH("ACTIVITY_LOG_SEARCH"),
	ACTION_REQUEST_REPORT("ACTION_REQUEST_REPORT"),

	;
	
	

	private final String actionType;

	private ActionType(String actionType) {
		this.actionType = actionType;
	}

	@Override
	public String toString() {
		return actionType;
	}

}
