package com.softcafe.constants;

public enum RsType {
	// comma separated enum
	
	RS_TYPE_USER("RS_TYPE_USER"),
	RS_TYPE_GROUP("RS_TYPE_GROUP"),
	RS_TYPE_TRIP("RS_TYPE_TRIP"),
	RS_TYPE_CLIENT("RS_TYPE_CLIENT"),
	RS_TYPE_PRODUCT("RS_TYPE_PRODUCT"),
	RS_TYPE_PORT("RS_TYPE_PORT"),
	RS_TYPE_HEAD("RS_TYPE_HEAD"),
	RS_TYPE_TRIP_POINT("RS_TYPE_TRIP_POINT"),
	RS_TYPE_SHIP("RS_TYPE_SHIP"),
	RS_TYPE_VICTIM("RS_TYPE_VICTIM"),
	RS_TYPE_INCIDENT("RS_TYPE_INCIDENT"),
	RS_TYPE_AMMUNATION_DATA("RS_TYPE_AMMUNATION_DATA"),
	RS_TYPE_AMMUNATION_SEARCH_DATA_REPORT("RS_TYPE_AMMUNATION_SEARCH_DATA_REPORT"),
	RS_TYPE_AMMUNATION_DATA_PDF("RS_TYPE_AMMUNATION_DATA_PDF"),
	RS_TYPE_NEQ_CALCULATION("RS_TYPE_NEQ_CALCULATION"),
	RS_TYPE_AMMUNATION_REPORT("RS_TYPE_AMMUNATION_REPORT"),
	RS_TYPE_LOADTABLE_ITEM_WISE("RS_TYPE_LOADTABLE_ITEM_WISE"),
	RS_TYPE_LOADTABLE_NOMANPLATURE_WISE("RS_TYPE_LOADTABLE_NOMANPLATURE_WISE"),
	RS_TYPE_AMMUNATION_DATA_NO_MAN_CLATURE("RS_TYPE_AMMUNATION_DATA_NO_MAN_CLATURE"),
	RS_TYPE_SEARCH_V2("RS_TYPE_SEARCH_V2"),
	
	

	RS_TYPE_IMAGE_NAME("RS_TYPE_IMAGE_NAME"),
	RS_TYPE_DOCS_NAME("RS_TYPE_DOCS_NAME"),
	RS_TYPE_VALUE_CONFIG("RS_TYPE_VALUE_CONFIG"),
	
	RS_TYPE_IED_INCIDENT_CAT("RS_TYPE_IED_INCIDENT_CAT"),
	RS_TYPE_INTENTION_CAT("RS_TYPE_INTENTION_CAT"),
	RS_TYPE_WEAPON("RS_TYPE_WEAPON"),
	RS_TYPE_TARGET_VICTIM("RS_TYPE_TARGET_VICTIM"),
	RS_TYPE_TARGET_VICTIM_SUBTYPE("RS_TYPE_TARGET_VICTIM_SUBTYPE"),
	RS_TYPE_CASUALITY_DEATH_BD("RS_TYPE_CASUALITY_DEATH_BD"),
	RS_TYPE_CASUALITY_INJURY_BD("RS_TYPE_CASUALITY_INJURY_BD"),
	RS_TYPE_CASUALITY_DEATH_MALI("RS_TYPE_CASUALITY_DEATH_MALI"),
	RS_TYPE_CASUALITY_INJURY_MALI("RS_TYPE_CASUALITY_INJURY_MALI"),
	RS_TYPE_CLASSIFICATION_DEATH_BD("RS_TYPE_CLASSIFICATION_DEATH_BD"),
	RS_TYPE_CLASSIFICATION_INJURY_BD("RS_TYPE_CLASSIFICATION_INJURY_BD"),
	
	RS_TYPE_CLASSIFICATION_DEATH_MALI("RS_TYPE_CLASSIFICATION_DEATH_MALI"),
	RS_TYPE_CLASSIFICATION_INJURY_MALI("RS_TYPE_CLASSIFICATION_INJURY_MALI"),
	
	RS_TYPE_IED_INCIDENT_TYPE_PIE_BD("RS_TYPE_IED_INCIDENT_TYPE_PIE_BD"),
	RS_TYPE_IED_INCIDENT_TYPE_PIE_MALI("RS_TYPE_IED_INCIDENT_TYPE_PIE_MALI"),
	RS_TYPE_LOADTABLE_DATA_LIST("RS_TYPE_LOADTABLE_DATA_LIST"),
	RS_TYPE_BRUNCH_LIST("RS_TYPE_BRUNCH_LIST"),
	RS_TYPE_STATE_LIST("RS_TYPE_STATE_LIST"),
	
	
	
	RS_TYPE_INCIDEBT_COUNT_MALI("RS_TYPE_INCIDEBT_COUNT_MALI"),
	RS_TYPE_INCIDEBT_COUNT_BD("RS_TYPE_INCIDEBT_COUNT_BD"),
	
	
	RS_TYPE_INCIDENT_COMMON("RS_TYPE_INCIDENT_COMMON"),
	RS_TYPE_DASHBOARD("RS_TYPE_DASHBOARD"),
	RS_TYPE_DASHBOARD_BAR_CHART("RS_TYPE_DASHBOARD_BAR_CHART"),
	RS_TYPE_NUMBER_OF_INCIDENT_BD("RS_TYPE_NUMBER_OF_INCIDENT_BD"),
	RS_TYPE_NUMBER_OF_INCIDENT_MALI("RS_TYPE_NUMBER_OF_INCIDENT_MALI"),
	RS_TYPE_NUMBER_OF_INCIDENT_MONTH_WISE_BD("RS_TYPE_NUMBER_OF_INCIDENT_MONTH_WISE_BD"),
	RS_TYPE_NUMBER_OF_INCIDENT_MONTH_WISE_MALI("RS_TYPE_NUMBER_OF_INCIDENT_MONTH_WISE_MALI"),
	RS_TYPE_YEARLY_INCIDENT_BD("RS_TYPE_YEARLY_INCIDENT_BD"),
	RS_TYPE_YEARLY_INCIDENT_MALI("RS_TYPE_YEARLY_INCIDENT_MALI"),
	RS_TYPE_LOCATION("RS_TYPE_LOCATION"),
	RS_TYPE_GENERIC_MAP("RS_TYPE_GENERIC_MAP"),
	
	RS_TYPE_COUNTRY("RS_TYPE_COUNTRY"),
	RS_TYPE_DIVISION("RS_TYPE_DIVISION"),
	RS_TYPE_DISTRICT("RS_TYPE_DISTRICT"),
	RS_TYPE_THANA("RS_TYPE_THANA"),
	
	RS_TYPE_DISTRICT_INCIDENT_BD("RS_TYPE_DISTRICT_INCIDENT_BD"),
	RS_TYPE_DISTRICT_INCIDENT_MALI("RS_TYPE_DISTRICT_INCIDENT_MALI"),
	RS_TYPE_MONTH_INCIDENT_BD("RS_TYPE_MONTH_INCIDENT_BD"),
	RS_TYPE_MONTH_INCIDENT_MALI("RS_TYPE_MONTH_INCIDENT_MALI"),
	RS_TYPE_MINASMA_INCIDENT("RS_TYPE_MINASMA_INCIDENT"),
	RS_TYPE_ROLE("RS_TYPE_ROLE"),
	RS_TYPE_UNASSIGN_ROLE("RS_TYPE_UNASSIGN_ROLE"),
	RS_TYPE_SEARCH("RS_TYPE_SEARCH"),
	
	
	RS_TYPE_IED_INCIDENT_TYPE_BD("RS_TYPE_IED_INCIDENT_TYPE_BD"),
	RS_TYPE_IED_INCIDENT_TYPE_MALI("RS_TYPE_IED_INCIDENT_TYPE_MALI"),
	RS_TYPE_FUSION_CONFIG("RS_TYPE_FUSION_CONFIG"),
	RS_TYPE_CAT_OF_INTENTION("RS_TYPE_CAT_OF_INTENTION"),
	RS_TYPE_CAT_OF_INCIDENT("RS_TYPE_CAT_OF_INCIDENT"),
	RS_TYPE_FUSION_CATAGORY("RS_TYPE_FUSION_CATAGORY"),
	RS_TYPE_WPN("RS_TYPE_WPN"),
	RS_TYPE_FIRE_ARMS("RS_TYPE_FIRE_ARMS"),
	RS_TYPE_CATAGORY("RS_TYPE_CATAGORY"),
	RS_TYPE_FILE_NAME("RS_TYPE_FILE_NAME"),
	RS_TYPE_CONFIGURED_OVERVIEW("RS_TYPE_CONFIGURED_OVERVIEW"),
	RS_TYPE_TYPE_OF_IED("RS_TYPE_TYPE_OF_IED"),
	RS_TYPE_SWITCH("RS_TYPE_SWITCH"),
	RS_TYPE_CAT_OF_THE_INCIDENT("RS_TYPE_CAT_OF_THE_INCIDENT"),
	RS_TYPE_CAT_OF_INTENSION("RS_TYPE_CAT_OF_INTENSION"),
	RS_TYPE_CAT_OF_THE_IED_INCIDENT("RS_TYPE_CAT_OF_THE_IED_INCIDENT"),
	
	RS_TYPE_TYPE_OF_WPN("RS_TYPE_TYPE_OF_WPN"),
	RS_TYPE_TYPE_IED("RS_TYPE_TYPE_IED"),
	RS_TYPE_TYPE_INDER_FIRE("RS_TYPE_TYPE_INDER_FIRE"),
	RS_TYPE_COMD_SWITCH("RS_TYPE_COMD_SWITCH"),
	RS_TYPE_RADIO_CON("RS_TYPE_RADIO_CON"),
	
	RS_TYPE_TIME_SWITCH("RS_TYPE_TIME_SWITCH"),
	RS_TYPE_TIME_MACHINACEL("RS_TYPE_TIME_MACHINACEL"),
	RS_TYPE_TIME_CHEMICAL("RS_TYPE_TIME_CHEMICAL"),
	RS_TYPE_TIME_ELECTRONIC("RS_TYPE_TIME_ELECTRONIC"),
	RS_TYPE_VICTIM_OPERATED_SWITCH("RS_TYPE_VICTIM_OPERATED_SWITCH"),
	RS_TYPE_PRESSURE("RS_TYPE_PRESSURE"),
	RS_TYPE_SENSOR("RS_TYPE_SENSOR"),
	
	RS_TYPE_TYPE_SWITCH("RS_TYPE_TYPE_SWITCH"),
	RS_TYPE_POWER_SOURCE("RS_TYPE_POWER_SOURCE"),
	
	RS_TYPE_INITIATOR("RS_TYPE_INITIATOR"),
	RS_TYPE_ELECTORNIC("RS_TYPE_ELECTORNIC"),
	RS_TYPE_NON_ELECTORNIC("RS_TYPE_NON_ELECTORNIC"),
	RS_TYPE_ELECTORNIC_COMMERCIAL_INITIATOR("RS_TYPE_ELECTORNIC_COMMERCIAL_INITIATOR"),
	RS_TYPE_ELECTORNIC_MILITARY_INITIATOR("RS_TYPE_ELECTORNIC_MILITARY_INITIATOR"),
	RS_TYPE_ELECTORNIC_IMPROVED_INITIATOR("RS_TYPE_ELECTORNIC_IMPROVED_INITIATOR"),
	RS_TYPE_NON_ELECTORNIC_COMMERCIAL_INITIATOR("RS_TYPE_NON_ELECTORNIC_COMMERCIAL_INITIATOR"),
	RS_TYPE_NON_ELECTORNIC_MILITARY_INITIATOR("RS_TYPE_NON_ELECTORNIC_MILITARY_INITIATOR"),
	RS_TYPE_NON_ELECTORNIC_IMPROVED_INITIATOR("RS_TYPE_NON_ELECTORNIC_IMPROVED_INITIATOR"),
	
	
	RS_TYPE_MAIN_CHANGE("RS_TYPE_MAIN_CHANGE"),
	RS_TYPE_HIGH_EXPLOSIVE("RS_TYPE_HIGH_EXPLOSIVE"),
	RS_TYPE_LOW_EXPLOSIVE("RS_TYPE_LOW_EXPLOSIVE"),
	RS_TYPE_MAIN_CHANGE_CONFIGURATION("RS_TYPE_MAIN_CHANGE_CONFIGURATION"),
	RS_TYPE_COMMERCIAL_HIGH_EXPLOSIVE("RS_TYPE_COMMERCIAL_HIGH_EXPLOSIVE"),
	RS_TYPE_MILITARY_HIGH_EXPLOSIVE("RS_TYPE_MILITARY_HIGH_EXPLOSIVE"),
	RS_TYPE_IMPROVE_HIGH_EXPLOSIVE_HME("RS_TYPE_IMPROVE_HIGH_EXPLOSIVE_HME"),
	RS_TYPE_MUNITIONS("RS_TYPE_MUNITIONS"),
	RS_TYPE_DEMOLITION_METERIALS("RS_TYPE_DEMOLITION_METERIALS"),
	RS_TYPE_COMMERCIAL_LOW_EXPLOSIVE("RS_TYPE_COMMERCIAL_LOW_EXPLOSIVE"),
	RS_TYPE_MILITARY_LOW_EXPLOSIVE("RS_TYPE_MILITARY_LOW_EXPLOSIVE"),
	RS_TYPE_IMPROVE_LOW_EXPLOSIVE_HME("RS_TYPE_IMPROVE_LOW_EXPLOSIVE_HME"),
	RS_TYPE_EXPLOSIVE_MIXTURES("RS_TYPE_EXPLOSIVE_MIXTURES"),
	RS_TYPE_PROPELLANTS("RS_TYPE_PROPELLANTS"),
	RS_TYPE_INCENDIARY("RS_TYPE_INCENDIARY"),
	RS_TYPE_DIRECTIONAL_EFFECT("RS_TYPE_DIRECTIONAL_EFFECT"),
	RS_TYPE_OMNI_DIRECTIONAL_BLAST_EFFECT("RS_TYPE_OMNI_DIRECTIONAL_BLAST_EFFECT"),
	RS_TYPE_IMPROVISED_PLATTER_CHARGE("RS_TYPE_IMPROVISED_PLATTER_CHARGE"),
	RS_TYPE_IMPROVISE_SHAPE_CHARGE("RS_TYPE_IMPROVISE_SHAPE_CHARGE"),
	RS_TYPE_CONTAINER("RS_TYPE_CONTAINER"),
	RS_FRAGMENTATION_MAT("RS_FRAGMENTATION_MAT"),
	RS_TYPE_TARGET_VICTIM_INFO("RS_TYPE_TARGET_VICTIM_INFO"),
	RS_TYPE_TARGET_VICTIM_TYPE("RS_TYPE_TARGET_VICTIM_TYPE"),
	RS_TYPE_TARGET_SUB_TYPE("RS_TYPE_TARGET_SUB_TYPE"),
	RS_TYPE_PERPETRATOR_GP_NAMEIDINFO("RS_TYPE_PERPETRATOR_GP_NAMEIDINFO"),
	RS_TYPE_SUSPECTED_PERPETRATORID("RS_TYPE_SUSPECTED_PERPETRATORID"),
	
	RS_TYPE_AGENCIES_INVOLVED("RS_TYPE_AGENCIES_INVOLVED"),
	
	//TODAY STARD
	RS_TYPE_AGENCIES_INVOLVED_FIRST("RS_TYPE_AGENCIES_INVOLVED_FIRST"),
	RS_TYPE_AGENCIES_INVOLVED_SECOND("RS_TYPE_AGENCIES_INVOLVED_SECOND"),
	RS_TYPE_AGENCIES_INVOLVED_THIRD("RS_TYPE_AGENCIES_INVOLVED_THIRD"),
	RS_TYPE_SPL_EQPT("RS_TYPE_SPL_EQPT"),
	RS_TYPE_SPL_EQPT_FIRST("RS_TYPE_SPL_EQPT_FIRST"),
	RS_TYPE_SPL_EQPT_SECOND("RS_TYPE_SPL_EQPT_SECOND"),
	RS_TYPE_TO_DISABLE_NEUTRALIZE_THE_IED("RS_TYPE_TO_DISABLE_NEUTRALIZE_THE_IED"),
	
	RS_TYPE_TYPE_OF_APPROACH("RS_TYPE_TYPE_OF_APPROACH"),
	RS_TYPE_TYPE_OF_ACTION("RS_TYPE_TYPE_OF_ACTION"),
	RS_TYPE_MAT_USER_1ST("RS_TYPE_MAT_USER_1ST"),
	RS_TYPE_MAT_USER_2ND("RS_TYPE_MAT_USER_2ND"),
	RS_TYPE_WAY_OF_RENDERING_THE_IED_SAFE("RS_TYPE_WAY_OF_RENDERING_THE_IED_SAFE"),
	RS_TYPE_UNPQ("RS_TYPE_UNPQ"),
	
	RS_TYPE_REGIONAL_BANGLADESH("RS_TYPE_REGIONAL_BANGLADESH"),
	RS_TYPE_REGIONAL_UNPKO("RS_TYPE_REGIONAL_UNPKO"),
	RS_TYPE_REGIONAL_GLOBAL("RS_TYPE_REGIONAL_GLOBAL"),
	RS_TYPE_REGIONAL("RS_TYPE_REGIONAL"),
	
	RS_TYPE_AMMUNITION_TYPE("RS_TYPE_AMMUNITION_TYPE"),
	RS_TYPE_DASHBOARD_BRANCH_IN("RS_TYPE_DASHBOARD_BRANCH_IN"),
	RS_TYPE_DASHBOARD_BRANCH_OUT("RS_TYPE_DASHBOARD_BRANCH_OUT"),
	RS_TYPE_DBL_DASHBOARD_STATE_IN_OUT("RS_TYPE_DBL_DASHBOARD_STATE_IN_OUT"),
	RS_TYPE_DBL_DASHBOARD_TOT_IN_OUT("RS_TYPE_DBL_DASHBOARD_TOT_IN_OUT"),

	
	
	
	
	
	
	RS_TYPE_CASUALITY_DEATH_INJURE_BD("RS_TYPE_CASUALITY_DEATH_INJURE_BD"),
	RS_TYPE_CASUALITY_DEATH_INJURE_MALI("RS_TYPE_CASUALITY_DEATH_INJURE_MALI"),
	
	RS_TYPE_CLAIM_OF_RESPONSIBILITY("RS_TYPE_CLAIM_OF_RESPONSIBILITY"),
	RS_TYPE_MODE_OF_CLAIM("RS_TYPE_MODE_OF_CLAIM"),
	RS_TYPE_OR_DATA("RS_TYPE_OR_DATA"),
	RS_TYPE_AMMO_TYPE_GROUP("RS_TYPE_AMMO_TYPE_GROUP"),
	
	;
	
	private final String rsType;

	private RsType(String rsType) {
		this.rsType = rsType;
	}
	
	
	@Override
	public String toString() {
		return rsType;
	}

	
	

}
